/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js and is kept here so the repo type-checks
// cleanly before the first local `next dev` run.
